### ISSUE TITLE
0.5.15 - Consistent Crash with Cobblemon Mod Installed

### ISSUE THREAD

**Issue by ARipeAppleByYoursTruly** [NathanPB/DeepMobLearning-fabric#149]
I was trying to customize my All of Fabric 7 v1.0.0 modpack with other mods, and found out that adding the Cobblemon mod will crash the modpack consistently

Looking at the crash report, I concluded that Cobblemon is conflicting with this mod in some way, through `ktdatataglib`, which listed under this mod only

I can reproduce the crash with the following steps:
1. On CurseForge, create a new profile with game version 1.20.1 and Fabric modloader 0.15.0
2. Install Deep Mob Learning: Refabricated through the "Add More Content" button
3. Run the game, it should not crash
4. Install Cobblemon through the "Add More Content" button
5. Run the profile, and try starting the game, the game should consistently crash

I tried again with Fabric modloader 0.15.1 and 0.14.25, still crashes consistently, so I assume Fabric modloader versions are not part of the reason

Repairing the profiles doesn't help as well

Here's the latest [crash report](https://pastebin.com/gqu2jmc2) from my testing

---

I can play All of Fabric 7 v0.63.0 with Cobblemon installed, so I looked into why it worked. I found out that changing Fabric Language Kotlin version from 1.10.10 to 1.10.12 will cause the crashes

For reference, All of Fabric 7 v0.63.0 has:
- game version 1.20.1
- Fabric modloader version 0.14.22
- Deep Mob Learning: Refabricated version 0.5.14
- Fabric Language Kotlin 1.10.10

Creating a new profile with just the mods in the specified versions above and installing Cobblemon will not crash the game, but updating Fabric Language Kotlin to 1.10.12 and up will crash the game

Should I report this issue to Fabric Language Kotlin instead?

**Comment by RemagOfficial** [comment]
use AOF7 1.0.1, this was fixed

**Comment by ARipeAppleByYoursTruly** [comment]
@RemagOfficial, can you test that on your end? Because it still crashes on my end. I only manage to successfully launch it by downgrading Fabric Language Kotlin to v1.10.11, it still crashes on v1.10.12 and up

Here's the latest [crash report](https://pastebin.com/LPCEH3uf) for AOF 7 v1.0.1 with only Cobblemon added and no other changes

I'm not sure if I should report this issue to here, Fabric Language Kotlin, or `ktdatataglib` itself

**Comment by Luligabi1** [comment]
Can you test if it works using Fabric Loader 0.14.25 or lower? It might be an issue brought on by the changes made on this version - as I've seen happen with other mods lately.

> I'm not sure if I should report this issue to here, Fabric Language Kotlin, or `ktdatataglib` itself

Keep the report here - it's definitely not an FLK issue and KTDataTagLib is an library developed by Nathan for DML.

**Comment by ARipeAppleByYoursTruly** [comment]
It will still crash through `ktdatataglib` until Fabric Loader 0.14.23 which Fabric loader reports mod incompatibility, so I created a new profile with Cobblemon and DML, and continued downgrading Fabric Loader. Still crashes through `ktdatataglib` until Fabric Loader 0.15.1 which it'll report mod incompatibility with Fabric API, so I stopped there.

---

You said that it's not an FLK issue, so I dug deeper and found https://github.com/FabricMC/fabric-language-kotlin/issues/130#issuecomment-1841508941, so I think this can be closed as a Cobblemon issue

**Comment by Luligabi1** [comment]
How bizarre, it's the last thing I'd ever expect 😅 thanks for digging it.
